# Generated by Django 5.1.7 on 2026-06-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_birth_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='body',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
