# Generated by Django 5.1.7 on 2026-06-03 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_user_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='body',
            field=models.CharField(default='n', max_length=50),
        ),
    ]
