# Generated by Django 5.1.7 on 2025-04-19 13:57

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('task_file', models.FileField(blank=True, null=True, upload_to='task_file_path')),
                ('url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('in_progress', 'درحال بررسی'), ('working', 'در حال انجام'), ('done', 'تکمیل شده'), ('error', ' به مشکل خورد'), ('rejected', 'رد شده')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_tasks', to=settings.AUTH_USER_MODEL)),
                ('main_responsible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_responsible_tasks', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_by_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('time', models.DateField(auto_now_add=True)),
                ('activity_file', models.FileField(blank=True, null=True, upload_to='task_file_path')),
                ('status', models.CharField(choices=[('in_progress', 'درحال بررسی'), ('working', 'در حال انجام'), ('done', 'تکمیل شده'), ('error', ' به مشکل خورد'), ('rejected', 'رد شده')], max_length=20)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL)),
                ('review_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_by', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='task.task')),
            ],
        ),
    ]
