# Generated by Django 5.1.7 on 2026-06-01 19:18

import django.db.models.deletion
import django_jalali.db.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('body', models.TextField(blank=True, default='.', null=True)),
                ('start_date', django_jalali.db.models.jDateField()),
                ('end_date', django_jalali.db.models.jDateField()),
                ('hours', models.DecimalField(decimal_places=2, max_digits=20)),
                ('videos', models.DecimalField(decimal_places=2, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', django_jalali.db.models.jDateField()),
                ('videos_number', models.DecimalField(decimal_places=2, max_digits=20)),
                ('hours_number', models.DecimalField(decimal_places=2, max_digits=20)),
                ('body', models.TextField(blank=True, default='.', null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_re', to='task.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_re', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
