# Generated by Django 5.1.7 on 2026-06-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_course_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='body',
            field=models.TextField(blank=True, default='.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='hours',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='course',
            name='videos',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, default='.'),
        ),
        migrations.AlterField(
            model_name='report',
            name='hours_number',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='report',
            name='videos_number',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
